### ISSUE TITLE
Update not possible -> Functionality limited

### ISSUE THREAD

**Issue by pecirep** [mariusmotea/diyHue#11]
Today there seems to be an update to the Hue Bridge. When I try to update, it fails. This is the output on the bridge: 

192.168.0.33 - - [10/Jun/2017 01:14:00] "POST /updater HTTP/1.1" 200 -
in post method
_----------------------------------------------------------------------------
Exception happened during processing of request from ('192.168.0.33', 39512)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "HueEmulator.py", line 596, in do_POST
    post_dictionary = json.loads(self.data_string)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
_----------------------------------------------------------------------------

I assume that the script is designed to be updated like a bridge, but how can the update be circumvented? I was not able to find any changelogs online that would indicate the version that I could then use in the json.config...

Edit: I added underscores in front of the rows with dashes as otherwise all of the text is displayed as a Header...

**Comment by mariusmotea** [comment]
In future i will add auto update functionality. For the moment check my last [commit ](https://github.com/mariusmotea/diyHue/commit/26a52c6655879711752034ad7b2d8abcc79bbeb6)to config.json. You need to change apiversion to 1.19.0 and swversion to 1705121051
