### ISSUE TITLE
Pyton Socket error

### ISSUE THREAD

**Issue by cad435** [mariusmotea/diyHue#125]
From time to time this error happens, than I could not connect to the bridge, nor switch lights on and off with ESP-based light switches

after pressing "CTRL+C" (I always start the Emulator as window) it works fine again...

Im not sure if its your code or caused by your code...

```

192.168.178.83 - - [20/Dec/2017 17:18:55] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.178.83', 33140)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
--------------------------------
```

another Error wich is in the log:
(I'm not sure wich one caused it)

```
192.168.178.26 - - [20/Dec/2017 17:19:20] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
192.168.178.26 - - [20/Dec/2017 17:19:32] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
192.168.178.23 - - [20/Dec/2017 17:19:33] "GET /description.xml HTTP/1.1" 200 -
^Cconfig saved
Traceback (most recent call last):
  File "./HueEmulator.py", line 1357, in <module>
    run()
  File "./HueEmulator.py", line 1347, in run
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
KeyboardInterrupt
Sending M Search response
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.178.45:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFE70FC4C
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-b827eb70fc4c::upnp:rootdevice
```

the IP address "192.168.178.83" is from a Logitech Harmony Hub wich supports HueBridge, but this Error might happened before the HarmonyHub got installed too, I'm not quite sure...

maybe you can do something about, will be cool...

greetings
cad435

**Comment by mariusmotea** [comment]
Are you using the latest version? This is happening because one or more requests to update the lights will fail. I had this issue in the past when multiple lights were unreachable, but now this was fixed for me.

**Comment by cad435** [comment]
I updated to the latest build an will see if it happens again...

It usually only crashes once a week or so...
