### ISSUE TITLE
Whitelist issue when only user remove the bridge

### ISSUE THREAD

**Issue by ticed35** [mariusmotea/diyHue#162]
Hello, 

An issue when the only user in whitelist is removed by deleting the hub on philips application. 
After it is impossible to add new user because whitelist option in config is removed. 

```
192.168.1.51 - - [26/Jan/2018 11:01:48] "GET /api/nouser/config HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.51', 52895)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "HueEmulator3.py", line 1236, in do_GET
    if url_pices[2] in bridge_config["config"]["whitelist"]: #if username is in whitelist
KeyError: 'whitelist'
----------------------------------------

```

**Comment by mariusmotea** [comment]
Hi,

I believe you tried to delete an username with DELETE request, but instead to delete just the user it delete entire whitelist key. In Hue API is not specified the deletion of anything from config (whitelist is there), so the code is simply waiting to provide the resource ID to delete, that is `url_pices[4]` in all the cases, except the users..

**Comment by ticed35** [comment]
Hi, 

Yes i saw a DELETE request on Hue-Emulator logs but it was made by the hue app that's why i ask you if it's normal.

**Comment by mariusmotea** [comment]
then is an issue, i never saw user delete requests from application (did you execute cleanup?), i will fix it.

**Comment by ticed35** [comment]
Hello, 
Sorry i forgot this point. 
Yes i delete from hue app but i have a second bridge that's why i'm available to remove this bridge on hue app (The remove button is only available when we are not connected on it).

**Comment by mariusmotea** [comment]
instead of: 

```
        self._set_headers()
        url_pices = self.path.split('/')
        if url_pices[2] in bridge_config["config"]["whitelist"]:
            del bridge_config[url_pices[3]][url_pices[4]]
            if url_pices[3] == "lights":
```

must be something like:
```
        self._set_headers()
        url_pices = self.path.split('/')
        if url_pices[2] in bridge_config["config"]["whitelist"]:
            if len(url_pices) == 6:
                del bridge_config[url_pices[3]][url_pices[4]][url_pices[5]]
            else:
                del bridge_config[url_pices[3]][url_pices[4]]
            if url_pices[3] == "lights":
```
i cannot test currently as i don't have two bridges.

**Comment by ticed35** [comment]
I test it and tell you if it works.
