### ISSUE TITLE
Philips TV won't find Hue Emulator

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#223]
Hi! I know it's going to be hard to fix it, but I wanted to report that the Hue Emulator is not discovered by my Philips TV (with Ambilight+Hue capabilities).

My TV runs Android 4.2.2 (Google TV) and it's on the latest available firmware (AND1E.0.10.170.0). The model is 55PUS7909/12

The Hue app finds the Hue Emulator just fine and it works nicely.

**Comment by mariusmotea** [comment]
Hmm, i have two different Philips tv's 6000 series, both discover the hue emulator and works ok. Can you insist a little bit with hue emulator discovery, maybe the tv did not catch the ssdp frames right away. In order to see what is happening at ssdp level you can start the script with sudo and provide the output.

**Comment by FezVrasta** [comment]
Just to make sure I'm doing it right. I should just go in the Ambilight+Hue settings and make it search for a new bridge right?

**Comment by mariusmotea** [comment]
Yes. Check if ssdp reply is send by hue emulator. You can also press the link button like you did to pair the phone

**Comment by FezVrasta** [comment]
Umh I get some weird log when I start it.

```
/opt/hue-emulator   6s
❯ sudo ./HueEmulator3.py                                                                         pi@raspberrypi
Config loaded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 111, in ssdpSearch
    sock.bind(server_address)
OSError: [Errno 98] Address already in use

start ssdp broadcast
sync with lights
Starting httpd...
----------------------------------------
Exception happened during processing of request from ('10.0.0.19', 33098)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [12/May/2018 10:48:37] "PUT /api/324/config/wifi/scanresult HTTP/1.1" 200 -
in PUT method
/api/324/config/wifi/scanresult
b'[{"rssi": -37.0, "ssid": "MiMoreWifi-2.5G", "channel": 4}, {"rssi": -65.0, "ssid": "SerenityLater", "channel": 11}, {"rssi": -81.0, "ssid": "Telekom-998558", "channel": 11}, {"rssi": -83.0, "ssid": "SMC", "channel": 6}]'
127.0.0.1 - - [12/May/2018 10:48:37] "PUT /api/324/config/wifi/updated HTTP/1.1" 200 -
in PUT method
/api/324/config/wifi/updated
b'{"status":"current-config", "mgmt":"0"}'
----------------------------------------
Exception happened during processing of request from ('10.0.0.19', 35586)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
-------------------
```

**Comment by mariusmotea** [comment]
If i'm not wrong you use deconz also? If yes, disable deconz ssdp service by editing systemd file and append `upnp=0`.

**Comment by mariusmotea** [comment]
Check this https://github.com/dresden-elektronik/deconz-rest-plugin/issues/274

**Comment by FezVrasta** [comment]
Thanks I tried that but I still get the same errors in the console 🤔

**Comment by mariusmotea** [comment]
`sudo netstat -lnup` to see exactry what service is using the port 1900/udp. Kill that process and it will work after.

**Comment by FezVrasta** [comment]
it was `minissdpd`, is it spawned by diyHue maybe?

**Comment by mariusmotea** [comment]
ssdpd server is native build in diyhue, minissdpd may de a default package in raspbian or is a dependency for something you had installed.

**Comment by FezVrasta** [comment]
umh ok thanks!
