### ISSUE TITLE
Alexa does not find the bridge

### ISSUE THREAD

**Issue by schnellecom** [mariusmotea/diyHue#251]
Hi I am very happy with the project and anything works fine but I just cannot find out how to discover the bridge with my Amazon Alexa.

If there is anything I am doing wrong I'm sorry in advance. Hope that you can help because than this would be an extremely awesome project

**Comment by mariusmotea** [comment]
Few months ago i fix ssdp broadcast messaged for alexa discovery. If something changed on how alexa discover the bridge i don't know. You can try to stop the hue-emulator service and run the script manually to see what it receive from Alexa during the discovery.
```
cd  /op/hue-emulator/
sudo./HueEmulator3.py
```

**Comment by mariusmotea** [comment]
Ahh, most likely you already have some ssdp services locally and the one from hue-emulator cannot broadcast. Check what service is using port 1900/udp

`sudo netstat -lnup`

**Comment by schnellecom** [comment]
So I tried manually starting the service and nothing changed. 

Here is the output of the netstat command (sorry I am a bit of a noob in rasbian so I don't understand):

pi@raspberrypi:/opt/hue-emulator $ sudo netstat -lnup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           378/avahi-daemon: r
udp        0      0 0.0.0.0:36090           0.0.0.0:*                           378/avahi-daemon: r
udp        0      0 0.0.0.0:68              0.0.0.0:*                           529/dhcpcd
udp6       0      0 :::5353                 :::*                                378/avahi-daemon: r
udp6       0      0 :::38427                :::*                                378/avahi-daemon: r

**Comment by mariusmotea** [comment]
Ok, no services are using port 1900/udp. Start HueEmulator3py script and ask alexa to discover the bridge.

**Comment by schnellecom** [comment]
So that does not work I still do not see any lights in the alexa app.

Maybe it is because my bridge does not have the update with the fixed ssdp broadcast message. 
How do I update the bridge? I tried running the install command but it just said the directory does already exist

**Comment by mariusmotea** [comment]
Provide here the output of the script during discovery. Ssdp for alexa was fixed long time ago. Anothe reason why you don,t se the lights is because they are not supported by Alexa.

**Comment by schnellecom** [comment]
I have some ESP8266 with WS2812 strips attached to them. 

Here is the output: (192.168.1.43 is my echo)
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
Starting ssl httpd...
192.168.1.21 - - [03/Jun/2018 11:17:03] "GET /description.xml HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.46
Sending M-Search response to 192.168.1.46
Sending M-Search response to 192.168.1.46
Sending M-Search response to 192.168.1.46
Sending M-Search response to 192.168.1.43
192.168.1.43 - - [03/Jun/2018 11:17:19] "GET /description.xml HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:19] "GET /api/ro0XIvGnV0bpyoILvRXV4VHs3QXjFM                                                                           XhXDZJBpFC/lights HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:19] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
Sending M-Search response to 192.168.1.43
192.168.1.43 - - [03/Jun/2018 11:17:21] "GET /description.xml HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:21] "GET /api/ro0XIvGnV0bpyoILvRXV4VHs3QXjFM                                                                           XhXDZJBpFC/lights HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:21] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
Sending M-Search response to 192.168.1.43
192.168.1.43 - - [03/Jun/2018 11:17:23] "GET /description.xml HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:23] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:23] "GET /api/ro0XIvGnV0bpyoILvRXV4VHs3QXjFM                                                                           XhXDZJBpFC/lights HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:23] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:23] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:24] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
Sending M-Search response to 192.168.1.43
192.168.1.43 - - [03/Jun/2018 11:17:25] "GET /description.xml HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:25] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:25] "GET /api/ro0XIvGnV0bpyoILvRXV4VHs3QXjFM                                                                           XhXDZJBpFC/lights HTTP/1.1" 200 -
192.168.1.43 - - [03/Jun/2018 11:17:25] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:25] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:25] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:27] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:27] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:28] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:29] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:30] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
192.168.1.43 - - [03/Jun/2018 11:17:30] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{"devicetype": "Echo"}'
Sending M-Search response to 192.168.1.39
Sending M-Search response to 192.168.1.21
192.168.1.21 - - [03/Jun/2018 11:17:47] "GET /description.xml HTTP/1.1" 200 -
192.168.1.21 - - [03/Jun/2018 11:17:47] "GET /description.xml HTTP/1.1" 200 -
192.168.1.21 - - [03/Jun/2018 11:17:47] "GET /description.xml HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.46
^Cconfig saved
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1454, in <module>
    sleep(10)
KeyboardInterrupt

**Comment by schnellecom** [comment]
Yes that did the trick thanks so much for the help

**Comment by haymaan** [comment]
can you please tell me how to link the diyhue to alexa ..?

**Comment by schnellecom** [comment]
You have to start the service manually and then it just worked after a while for me. I did reinstall it with an updated OS on the pi in between but I can not tell you if that helped.

**Comment by haymaan** [comment]
When I want to activate the skill it's took me to meethue.com to link my bridge ,and there I can't link any bridge to it ???

**Comment by schnellecom** [comment]
You don't need the skill because it works with the default app build into alexa. 

Did you press the button on http://{IP_ADRESS}/hue/linkbutton and if yes please post the output if you press that and search with alexa from the manual script.

**Comment by haymaan** [comment]
That's works nice thank you

**Comment by krulkip** [comment]
Still stuggling to get alexa to discover bridge / devices / scenes.
Stooped thes ervice and then manually ran HueEmulator. Following reply.
I can use hue app as normal. My bridge is at 192.168.0.40 so not sure what 18 and 17 means.
Can someone help ?

pi@raspberrypi:~/diyhue/diyHue/BridgeEmulator $ sudo ./HueEmulator3.py
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1566, in run
    ctx.load_cert_chain(certfile="./cert.pem")
ssl.SSLError: [SSL] PEM lib (_ssl.c:2964)

192.168.0.18 - - [23/Sep/2018 12:21:57] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:02] "GET /description.xml HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:02] "GET /api/ZB0Tmwz7ikRDiN89JdjUMSVn1JWSV6iPMDG1kknF/lights HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:02] "POST /api HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:03] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:03] "GET /description.xml HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:03] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:05] "GET /description.xml HTTP/1.1" 200 -
192.168.0.17 - - [23/Sep/2018 12:22:05] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/diyhue/diyHue/BridgeEmulator/functions/ssdp.py", line 28, in ssdpSearch
    data = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 523: invalid start byte

**Comment by krulkip** [comment]
I think 18 is my pc and 17 the alexa. I did use the installation script.

**Comment by braini1511** [comment]
Hi Marius,
first thanks for your work here. It is really sweet stuff.

I got also no chance to connect to Alexa. But i also can't start theHueEmulater3.py manually. I am not able to find the diyhue folder in the home directory. I try ll but nothing. Is this correct?
Restart of the System does not work, and the Install was by automatic. Or can Alexa just operate with real Hue-Lights? And not with ESP8266-Lights?

**Comment by braini1511** [comment]
Hi, thanks for help, found ist ;)
But i got a lot of exceptions:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 128, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1717, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1704, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR:root:light 9 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb4f18670>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb4f18670>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./HueEmulator3.py", line 790, in syncWithLights
    light_data = json.loads(sendRequest("http://" + bridge_config["lights_address"][light]["ip"] + "/get?light=" + str(bridge_config["lights_address"][light]["light_nr"]), "GET", "{}"))
  File "./HueEmulator3.py", line 546, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb4f18670>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))
ERROR:root:light 10 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb14007f0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=3 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb14007f0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./HueEmulator3.py", line 790, in syncWithLights
    light_data = json.loads(sendRequest("http://" + bridge_config["lights_address"][light]["ip"] + "/get?light=" + str(bridge_config["lights_address"][light]["light_nr"]), "GET", "{}"))
  File "./HueEmulator3.py", line 546, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=3 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb14007f0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))
ERROR:root:light 8 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb1406ab0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb1406ab0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./HueEmulator3.py", line 790, in syncWithLights
    light_data = json.loads(sendRequest("http://" + bridge_config["lights_address"][light]["ip"] + "/get?light=" + str(bridge_config["lights_address"][light]["light_nr"]), "GET", "{}"))
  File "./HueEmulator3.py", line 546, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.55', port=80): Max retries exceeded with url: /get?light=1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb1406ab0>, 'Connection to 192.168.1.55 timed out. (connect timeout=3)'))

The question still is: Can Alexa control Light-bulbs based on ESP8266 via DIYHUE?

Best regards

**Comment by mariusmotea** [comment]
Stop the service hue-emulator first because it cannot be started two times as the ports are already in use.
```
sudo systemctl stop hue-emulator
```

**Comment by mariusmotea** [comment]
The Hue Account will not work, there is a remote API used with authentication from original bridge to Philips cloud servers. I hear that i possible to use home assistant as proxy to apply color scenes from Alexa.

**Comment by braini1511** [comment]
Ok thanks you for that. Alexa integration is no keyfeature for me, so don‘t care aboit that. It needs to work good with App ans Sensors and that works fine!

**Comment by LinoJo** [comment]
Hi Marius, i got an other error. Can you help me?

**ConnectionResetError: [Errno 104] Connection reset by peer**

I've tryed to connect the hue-emulator with alexa with the Alexa app on my phone (192.168.1.37)
My PC is the 192.168.1.59.

Debug:

`192.168.1.59 - - [14/Jul/2020 20:02:57] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -`
`2020-07-14 20:02:58,281 - root - DEBUG - Sending M-Search response to 192.168.1.59`
`2020-07-14 20:02:59,600 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443`
`2020-07-14 20:02:59,903 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6 {"ok"}`
`----------------------------------------`
`Exception happened during processing of request from ('192.168.1.37', 43426)`
`Traceback (most recent call last):`
`File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread`
`self.finish_request(request, client_address)`
`File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request`
`self.RequestHandlerClass(request, client_address, self)`
`File "/usr/lib/python3.7/socketserver.py", line 720, in __init__`
`self.handle()`
`File "/usr/lib/python3.7/http/server.py", line 428, in handle`
`self.handle_one_request()`
`File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request`
`self.raw_requestline = self.rfile.readline(65537)`
`File "/usr/lib/python3.7/socket.py", line 589, in readinto`
`return self._sock.recv_into(b)`
`File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into`
`return self.read(nbytes, buffer)`
`File "/usr/lib/python3.7/ssl.py", line 911, in read`
`return self._sslobj.read(len, buffer)`
`ConnectionResetError: [Errno 104] Connection reset by peer`
`----------------------------------------`
`2020-07-14 20:03:14,320 - root - DEBUG - Sending M-Search response to 192.168.1.59`
`2020-07-14 20:03:26,439 - root - DEBUG - Sending M-Search response to 192.168.1.71`
`2020-07-14 20:03:27,042 - root - DEBUG - Sending M-Search response to 192.168.1.71`
`2020-07-14 20:03:29,950 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443`
`2020-07-14 20:03:30,342 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6 {"ok"}`
