### ISSUE TITLE
New ZGPSwitch

### ISSUE THREAD

**Issue by thetemplar** [mariusmotea/diyHue#311]
I flashed a NodeMCU with  diyHue/Sensors/HueTapSwitch/HueTapSwitch.ino and get an exception in the HueEmulator3.py script on connect:

```
192.168.178.200 - - [09/Aug/2018 18:32:55] "GET /switch?devicetype=ZGPSwitch&mac=68:c6:3a:c3:78:36 HTTP/1.1" 200 -
{'devicetype': ['ZGPSwitch'], 'mac': ['68:c6:3a:c3:78:36']}
----------------------------------------
Exception happened during processing of request from ('192.168.178.200', 49154)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1251, in do_GET
    if bridge_config["sensors"][sensor]["uniqueid"].startswith(get_parameters["mac"][0]): # if sensor is already present
KeyError: 'uniqueid'
----------------------------------------
```

The TapSwitch does not appear in the GUI.

**Comment by mariusmotea** [comment]
Hi,

Issue was introduced with new built in daylight sensor that don't have uniqueid key. I discover this issue while i'm refactoring the motion sensors and i add the fix in develop branch. Just replace the HueEmulator3.py script with the one from here: https://github.com/mariusmotea/diyHue/blob/develop/BridgeEmulator/HueEmulator3.py

**Comment by thetemplar** [comment]
Works, ty
