### ISSUE TITLE
Cannot connect to HueEmulator via Hue App (SSL-Error)

### ISSUE THREAD

**Issue by SillyTones** [mariusmotea/diyHue#322]
Hi 
I just installed deConz and HueEmulator on my RPi2. The Hue App can find the bridge but when i activate the /hue/linkbutton it doesn't do anything.
I ran HueEmulator3.py manually and saw an SSL Error:
```
sudo ./HueEmulator3.py
Config loaded
Starting deconz websocket
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1682, in run
    ctx.load_cert_chain(certfile="./cert.pem")
ssl.SSLError: [SSL] PEM lib (_ssl.c:2943)
```
How can i fix that?

Thanks for your help

**Comment by mariusmotea** [comment]
please show output for command:

`cat /opt/hue-emulator/cert.pem`

i believe the certificate was not downloaded correctly. Not sure if is related, but are you using latest versions of python3 and openssl?

**Comment by SillyTones** [comment]
Just checked.. python3 and openssl are the latest versions..
The file cert.pem exists in the folder, but seems to be empty. So yes it was not downloaded correctly.
Where can i download the certificate??

**Comment by mariusmotea** [comment]
then execute  `curl "http://mariusmotea.go.ro:9002/gencert?mac=00:11:22:33:44:55"` and put the output in that file. Please note that you must replace 00:11:22:33:44:55 with the mac address of your device. In case you still have issues try to wipe from application data.

**Comment by SillyTones** [comment]
ip a (i have Hamachi running for VPN connection)
```

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ham-br0 state UP group default qlen 1000
    link/ether b8:27:eb:66:49:b4 brd ff:ff:ff:ff:ff:ff
3: ham0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1404 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 7a:79:19:27:93:14 brd ff:ff:ff:ff:ff:ff
    inet 25.39.147.20/8 brd 25.255.255.255 scope global ham0
       valid_lft forever preferred_lft forever
    inet 169.254.249.213/16 brd 169.254.255.255 scope global ham0
       valid_lft forever preferred_lft forever
    inet6 2620:9b::1927:9314/96 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::7879:19ff:fe27:9314/64 scope link
       valid_lft forever preferred_lft forever
4: ham-br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1404 qdisc noqueue state UP group default qlen 1000
    link/ether 00:23:c3:27:93:14 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.10/24 brd 192.168.2.255 scope global ham-br0
       valid_lft forever preferred_lft forever
    inet 192.168.2.74/24 brd 192.168.2.255 scope global secondary ham-br0
       valid_lft forever preferred_lft forever
    inet6 fe80::beaa:b441:9497:3800/64 scope link
       valid_lft forever preferred_lft forever
5: ham1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1404 qdisc pfifo_fast master ham-br0 state UNKNOWN group default qlen 1000
    link/ether 00:23:c3:27:93:14 brd ff:ff:ff:ff:ff:ff
    inet 169.254.115.238/16 brd 169.254.255.255 scope global ham1
       valid_lft forever preferred_lft forever
    inet6 fe80::223:c3ff:fe27:9314/64 scope link
       valid_lft forever preferred_lft forever

```

And curl:

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=b827ebfffe6649b4
*  start date: Aug 15 20:35:00 2018 GMT
*  expire date: Aug 12 20:35:00 2028 GMT
*  issuer: C=NL; O=Philips Hue; CN=b827ebfffe6649b4
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 17 Aug 2018 16:45:14 GMT
< Content-type: application/json
< Content-Length: 227
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"factorynew":false,"replacesbridgeid":null,"starterkitid":"","mac":"7a:79:19:27:93:14","bridgeid":"7A7919FFFE279314","swversion":"1806051111","datastoreversion":70,"modelid":"BSB002","name":"Philips hue","apiversion":"1.24.0"}

```

**Comment by mariusmotea** [comment]
The issue seams to be generated by Hamachi interface. I don't know any nice fix than to edit the file HueEmulator3.py and hardcode the mac address. You will need to perform this change every time:

`mac = '%012x' % get_mac()`
replace with:
`mac = "b827eb6649b4"`

If ip address is also taken from Hamachi interface then:

```
def getIpAddress():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    return s.getsockname()[0]
```
replace with:
```
def getIpAddress():
    return "192.168.x.x"
```

from ip a command i see you don't have ip on physical interface of raspberry, witch is wired.

**Comment by mariusmotea** [comment]
I believe this was fixed when we replace ip detection method

**Comment by cheesemarathon** [comment]
In that case, surely this can be closed?
