### ISSUE TITLE
Hue lights found but not added to config.json

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#327]
When I pair my DeCONZ it says "15 lights found" but then in the config.json and in the web app I don't see any.

Maybe the file permissions are wrong? What's the right setting for them?

**Comment by mariusmotea** [comment]
config.json is not saved in real time, it is saved automatically every hour and when a new object is created. Can be saved also with GET request to /save. Because there is no light in web app i believe there is an error during the import phase. Can you start the script manually and check the output during lights import?

**Comment by mariusmotea** [comment]
One more thing, in web gui you will see only the lights added in rooms, so is possible that everything works fine, you only need to create the rooms from hue application

**Comment by FezVrasta** [comment]
Thanks, after I ran /save manually the lights appeared in the config, but not in the UI, even if my lights are part of a group.

**Comment by FezVrasta** [comment]
```
❯ sudo python3 HueEmulator3.py                                                                                                                                    pi@raspberrypi
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
light 1 is unreachable
light 9 is unreachable
light 11 is unreachable
light 4 is unreachable
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 1680, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

light 3 is unreachable
light 12 is unreachable
light 6 is unreachable
light 8 is unreachable
light 7 is unreachable
light 13 is unreachable
light 5 is unreachable
10.0.0.6 - - [18/Aug/2018 09:08:32] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
10.0.0.6 - - [18/Aug/2018 09:08:33] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
10.0.0.19 - - [18/Aug/2018 09:08:40] "GET /api/config HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
10.0.0.7 - - [18/Aug/2018 09:08:45] "GET /api/nouser/config HTTP/1.1" 200 -
10.0.0.19 - - [18/Aug/2018 09:08:45] "GET /api/3d690227-f/config HTTP/1.1" 200 -
10.0.0.19 - - [18/Aug/2018 09:08:50] "GET /api/3d690227-f/groups HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.10
10.0.0.7 - - [18/Aug/2018 09:08:54] "GET /api/nouser/config HTTP/1.1" 200 -
10.0.0.6 - - [18/Aug/2018 09:08:56] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
```

**Comment by mariusmotea** [comment]
The lights must be attached to groups in hue emulator, not deconz, in order to be visible. If Hue app refuse to pair it may be because it cache the old certificate, and the new certificate is different. To be sure that this is the problem execute curl https://127.0.0.1 -v -k from emulator host. If certificate CN is identical with displayed bridgeid from output json then you need to wipe hue app data and try again.

**Comment by mariusmotea** [comment]
Something else is using port 80 or/and 443.  If you did not stop hue emulator service, then the ports may be used by hue emulator.

**Comment by FezVrasta** [comment]
I uninstalled the app and installed it over but it still doesn't pair :-( (I'm on iOS)

**Comment by mariusmotea** [comment]
I don't believe your aproach is working because "Address already in use" error. You need to change deconz ports like i specify in the wiki.

**Comment by FezVrasta** [comment]
I also tried with DeCONZ turned off, no luck

**Comment by mariusmotea** [comment]
Once hue emulator is paired with deconz it is trying to connect on websocket during startup and in case of errors it may fail. In config.json there is the key deconz=>enabled witch now must be True. Switch to false if you don't want to use sensors/remotes.

**Comment by FezVrasta** [comment]
I see, thanks!

**Comment by FezVrasta** [comment]
I'm getting this error now that I moved DeCONZ to a different port following the wiki instructions... :-(

```
❯ sudo python3 HueEmulator3.py                                                                                                                                    pi@raspberrypi
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/14 HTTP/1.1" 200 -
light 7 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/2 HTTP/1.1" 200 -
light 5 is unreachable
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 1682, in run
    ctx.load_cert_chain(certfile="./cert.pem")
ssl.SSLError: [SSL] PEM lib (_ssl.c:2943)

light 17 is unreachable
light 28 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/18 HTTP/1.1" 200 -
light 11 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/16 HTTP/1.1" 200 -
light 9 is unreachable
light 26 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/4 HTTP/1.1" 200 -
light 1 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/9 HTTP/1.1" 200 -
light 3 is unreachable
light 19 is unreachable
light 18 is unreachable
light 25 is unreachable
light 29 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/5 HTTP/1.1" 200 -
light 4 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:07] "GET /api/4956946779/lights/15 HTTP/1.1" 200 -
light 6 is unreachable
light 16 is unreachable
light 23 is unreachable
light 21 is unreachable
light 20 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/17 HTTP/1.1" 200 -
light 15 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/8 HTTP/1.1" 200 -
light 14 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/19 HTTP/1.1" 200 -
light 12 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/3 HTTP/1.1" 200 -
light 8 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/13 HTTP/1.1" 200 -
light 2 is unreachable
light 30 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/7 HTTP/1.1" 200 -
light 13 is unreachable
10.0.0.19 - - [18/Aug/2018 12:41:08] "GET /api/4956946779/lights/6 HTTP/1.1" 200 -
light 10 is unreachable
light 22 is unreachable
light 27 is unreachable
light 24 is unreachable
Sending M-Search response to 10.0.0.2
10.0.0.2 - - [18/Aug/2018 12:41:14] "GET /description.xml HTTP/1.1" 200 -
10.0.0.19 - - [18/Aug/2018 12:41:17] "GET /api/config HTTP/1.1" 200 -
10.0.0.7 - - [18/Aug/2018 12:41:20] "GET /api/nouser/config HTTP/1.1" 200 -
10.0.0.7 - - [18/Aug/2018 12:41:20] "GET /api/nouser/config HTTP/1.1" 200 -
10.0.0.19 - - [18/Aug/2018 12:41:22] "GET /api/3d690227-f/config HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.7
Sending M-Search response to 10.0.0.2
10.0.0.6 - - [18/Aug/2018 12:41:24] "GET /hue/linkbutton?username=&password=znvWAf6QT8j3%2B%5B6dhK%5DC%3D9DaDg%2C&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.18
Sending M-Search response to 10.0.0.6
10.0.0.19 - - [18/Aug/2018 12:41:27] "GET /api/3d690227-f/groups HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.6
Sending M-Search response to 10.0.0.6
Sending M-Search response to 10.0.0.6
10.0.0.6 - - [18/Aug/2018 12:41:31] "GET /hue/linkbutton?username=&password=znvWAf6QT8j3%2B%5B6dhK%5DC%3D9DaDg%2C&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.10
Sending M-Search response to 10.0.0.2
127.0.0.1 - - [18/Aug/2018 12:41:34] "PUT /api/273/config/wifi/scanresult HTTP/1.1" 200 -
in PUT method
/api/273/config/wifi/scanresult
b'[{"rssi": -36.0, "ssid": "MiMoreWifi-guest", "channel": 1}, {"rssi": -82.0, "ssid": "Telekom-998558", "channel": 1}, {"rssi": -36.0, "ssid": "MiMoreWifi", "channel": 1}, {"rssi": -68.0, "ssid": "Judit Misko", "channel": 1}, {"rssi": -78.0, "ssid": "SerenityLater", "channel": 11}]'
127.0.0.1 - - [18/Aug/2018 12:41:34] "PUT /api/273/config/wifi/updated HTTP/1.1" 200 -
in PUT method
/api/273/config/wifi/updated
b'{"status":"current-config", "mgmt":"0"}'
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
10.0.0.6 - - [18/Aug/2018 12:41:43] "GET /hue/linkbutton?username=&password=znvWAf6QT8j3%2B%5B6dhK%5DC%3D9DaDg%2C&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
Sending M-Search response to 10.0.0.2
10.0.0.2 - - [18/Aug/2018 12:42:03] "GET /description.xml HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.2
127.0.0.1 - - [18/Aug/2018 12:42:05] "PUT /api/273/config/wifi/scanresult HTTP/1.1" 200 -
in PUT method
/api/273/config/wifi/scanresult
b'[{"rssi": -39.0, "ssid": "MiMoreWifi-guest", "channel": 1}, {"rssi": -82.0, "ssid": "Telekom-998558", "channel": 1}, {"rssi": -37.0, "ssid": "MiMoreWifi", "channel": 1}, {"rssi": -69.0, "ssid": "Judit Misko", "channel": 1}, {"rssi": -82.0, "ssid": "SerenityLater", "channel": 11}, {"rssi": -83.0, "ssid": "KOVACS_WIFI", "channel": 6}, {"rssi": -77.0, "ssid": "SMC", "channel": 6}]'
127.0.0.1 - - [18/Aug/2018 12:42:06] "PUT /api/273/config/wifi/updated HTTP/1.1" 200 -
in PUT method
/api/273/config/wifi/updated
b'{"status":"current-config", "mgmt":"0"}'
Sending M-Search response to 10.0.0.2
```

**Comment by FezVrasta** [comment]
Actually, with this https://github.com/mariusmotea/diyHue/issues/322#issuecomment-413245336 I fixed that error, but I still can't link the bridge to the app 🙄

**Comment by mariusmotea** [comment]
can you provide again output of the commands `ip a` and `curl https://127.0.0.1/api/nouser -v -k` to validate your certificate is correct for used intertface?

**Comment by FezVrasta** [comment]
````
~
❯ ip a                                                                                                                                                            pi@raspberrypi
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:aa:e9:3f brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.19/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.20/24 brd 10.0.0.255 scope global secondary eth0:1
       valid_lft forever preferred_lft forever
    inet6 fe80::8965:2da7:c92e:51ab/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:ff:bc:6a brd ff:ff:ff:ff:ff:ff

~
❯ curl https://127.0.0.1/api/nouser -v -k                                                                                                                         pi@raspberrypi
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=001122fffe334455
*  start date: Aug 18 12:44:53 2018 GMT
*  expire date: Aug 15 12:44:53 2028 GMT
*  issuer: C=NL; O=Philips Hue; CN=001122fffe334455
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Sat, 18 Aug 2018 12:53:52 GMT
< Content-type: application/json
< Content-Length: 227
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"modelid":"BSB002","datastoreversion":70,"bridgeid":"B827EBFFFEAAE93F","name":"Philips hue","starterkitid":"","replacesbridgeid":null,"swversion":"1806051111","mac":"b8:27:eb:aa:e9:3f","apiversion":"1.24.0","factorynew":false}%
```

**Comment by mariusmotea** [comment]
you made a mistake, CN=001122fffe334455, you left the mac address from example (00:11:22:33:44:55).

request new cert with your mac address b8:27:eb:aa:e9:3f. Will not work if you will not erase the hue application cache again.

**Comment by FezVrasta** [comment]
oh :-( Thanks!

It works now 😍
