### ISSUE TITLE
Current diyHue version incompatible with latest Hue Android app

### ISSUE THREAD

**Issue by velijv** [mariusmotea/diyHue#419]
Used to work great, but after updating the Hue android app it shows an error message " App functionality is limited until you upgrade your Hue system "

**Comment by cooltom** [comment]
same for me. as i reported here https://github.com/mariusmotea/diyHue/issues/382#issuecomment-426102723
Seems like all HUE apps updated to some "new hue standard". So I guess puss button not return something what new apps expect ...

**Comment by mariusmotea** [comment]
Yes, when you click update button the needed values on bridge will be updated to new version, but application reply is not the expected one so will popup the message "Update failed", but if you close the application and open it again the bridge will be up to date with no limitations.

**Comment by cheesemarathon** [comment]
Non issue. Solution is explained by Marius so closing this.

**Comment by velijv** [comment]
I would like to say this is resolved, but for the Android app at least, the update keeps spinning and not completing - even when letting it run 10 minutes, closing the app and restarting it. 
![2018-11-04 10 44 44](https://user-images.githubusercontent.com/5716539/48055284-e4482c00-e1b7-11e8-91aa-1ccaf2f4c336.jpg)
![2018-11-04 10 44 53](https://user-images.githubusercontent.com/5716539/48055285-e4e0c280-e1b7-11e8-80bd-63524bdde92e.jpg)

**Comment by cheesemarathon** [comment]
@velijv Can you [enable debugging](https://github.com/mariusmotea/diyHue/wiki/Debug#enable-debug-mode) and post the output from the diyHue script when you try an update from the app?

**Comment by velijv** [comment]
`OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:10] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:11] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:13] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:13] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:14,733 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:15] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:15,697 - root - ERROR - light 7 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 114, in get_light_state
    data = tcp_socket.recv(16 * 1024)
socket.timeout: timed out
192.168.1.116 - - [08/Nov/2018 11:47:17] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:18,785 - root - ERROR - light 6 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state
    tcp_socket.connect((ip, int(55443)))
OSError: [Errno 113] No route to host
192.168.1.140 - - [08/Nov/2018 11:47:19] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:19] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:21] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:21] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:23] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:24,479 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:25] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:25] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:27] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:29] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:30,300 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:31] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
2018-11-08 11:47:31,403 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:31] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:32] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-11-08 11:47:32,852 - root - DEBUG - sync with lights
192.168.1.116 - - [08/Nov/2018 11:47:34] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:35,080 - root - DEBUG - Sending M-Search response to 192.168.1.231
2018-11-08 11:47:35,985 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state
    tcp_socket.connect((ip, int(55443)))
OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:36] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:37] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:38] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:39,105 - root - ERROR - light 15 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state
    tcp_socket.connect((ip, int(55443)))
OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:40] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:42] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:42] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:43] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
2018-11-08 11:47:44,393 - root - ERROR - light 7 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 114, in get_light_state
    data = tcp_socket.recv(16 * 1024)
socket.timeout: timed out
192.168.1.116 - - [08/Nov/2018 11:47:44] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:46] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:47,505 - root - ERROR - light 6 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 735, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state
    tcp_socket.connect((ip, int(55443)))
OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:48] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:49] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:50] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:51,076 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:52] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:52] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:54,981 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:55] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:55] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -`

**Comment by cheesemarathon** [comment]
Any ideas @mariusmotea? Better formatted logs:
```
OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:10] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:11] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:13] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:13] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:14,733 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:15] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:15,697 - root - ERROR - light 7 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 114, in get_light_state data = tcp_socket.recv(16 * 1024) socket.timeout: timed out
192.168.1.116 - - [08/Nov/2018 11:47:17] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:18,785 - root - ERROR - light 6 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state tcp_socket.connect((ip, int(55443))) OSError: [Errno 113] No route to host
192.168.1.140 - - [08/Nov/2018 11:47:19] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:19] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:21] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:21] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:23] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:24,479 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:25] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:25] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:27] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:29] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:30,300 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:31] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
2018-11-08 11:47:31,403 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:31] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:32] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-11-08 11:47:32,852 - root - DEBUG - sync with lights
192.168.1.116 - - [08/Nov/2018 11:47:34] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 - 
2018-11-08 11:47:35,080 - root - DEBUG - Sending M-Search response to 192.168.1.231
2018-11-08 11:47:35,985 - root - ERROR - light 1 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state tcp_socket.connect((ip, int(55443))) OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:36] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:37] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:38] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:39,105 - root - ERROR - light 15 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state tcp_socket.connect((ip, int(55443))) OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:40] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:42] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:42] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:43] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
2018-11-08 11:47:44,393 - root - ERROR - light 7 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 114, in get_light_state data = tcp_socket.recv(16 * 1024) socket.timeout: timed out
192.168.1.116 - - [08/Nov/2018 11:47:44] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:46] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:47,505 - root - ERROR - light 6 is unreachable Traceback (most recent call last):
	File "./HueEmulator3.py", line 735, in syncWithLights light_state = protocol.get_light_state(bridge_config["lights_address"][light]["ip"], bridge_config["lights"][light])
	File "/opt/hue-emulator/protocols/yeelight.py", line 111, in get_light_state tcp_socket.connect((ip, int(55443))) OSError: [Errno 113] No route to host
192.168.1.116 - - [08/Nov/2018 11:47:48] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.1.140 - - [08/Nov/2018 11:47:49] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:50] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:51,076 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.116 - - [08/Nov/2018 11:47:52] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:52] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-11-08 11:47:54,981 - root - DEBUG - Sending M-Search response to 192.168.1.231
192.168.1.140 - - [08/Nov/2018 11:47:55] "GET /api/470a0c52e89555f73b11904c84af6192/lights HTTP/1.1" 200 -
192.168.1.116 - - [08/Nov/2018 11:47:55] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
```
I assume 192.168.1.231 is the IP of your phone @velijv?

**Comment by cheesemarathon** [comment]
@mariusmotea should we see the update request in the logs?

**Comment by mariusmotea** [comment]
@velijv please provide me pastebin.com link with your config.json. I will fix this for you. Or you can try to do it by youre self. in config.json look for "config" => "swversion" and set this to value "1809121051". Ensure you stop hue-emulator service first in order to not override your changes. I believe you don't have internet access to your device to update that value automatically from this repo (`No route to host` errors)

**Comment by velijv** [comment]
@mariusmotea - I changed the swversion to the new value, and use a new device to connect the bridge. It shows "1 device found" in Hue app, but clicking pair (and activating linkbutton) does not pair them, and can not use the app. 

This is my config.json - https://pastebin.com/WcS2PydZ

**Comment by mariusmotea** [comment]
I believe there are some issues with the new hue app but at this moment we don't know what is the issue may be Some parameters in config i guess...

**Comment by erazor666** [comment]
It works fine from within home assistant for instance. This might not be a major thing i'm guessing, but its beyond me to figure it out, if you need debug from another system i can probably come up with it(?)

**Comment by velijv** [comment]
> 
> 
> I believe there are some issues with the new hue app but at this moment we don't know what is the issue may be Some parameters in config i guess...

Still doesn't work after deleting all app data. Is there a way to reset my config.json to try anew?

**Comment by mariusmotea** [comment]
delete entire /opt/hue-emulator folder and run the auto install script. Delete hue application data then try to pair it.

Marius.

**Comment by velijv** [comment]
Reinstalling worked, thank you!

**Comment by cheesemarathon** [comment]
Closing as fixed
